	package javalab;

import java.util.Scanner;

public class Exception {
public static void main(String[]args) {
	Scanner sc=new Scanner(System.in);
	char c=0;
	do {
	System.out.println("choose an operation");
	System.out.println("1.Arithmetic operation");
	System.out.println("2.Array Acess");
		 int choice= sc.nextInt();
		switch(choice) {
	case 1:
		try {
			System.out.println("enter Numerator");
			int Num=sc.nextInt();
			System.out.println("enter Denominator");
			int Deno=sc.nextInt();
			int Result= Num/Deno;
			System.out.println("Result="+Result);
		}
		catch( ArithmeticException e) {
			System.out.println("caught an exception:"+e.getMessage());
		}
		break;
	case 2:
		int[]numbers= {1,2,3};
		try {
			System.out.println("enter array to index");
			int index=sc.nextInt();
			System.out.println("element at index"+ index +":"+numbers[index]);
		}
		catch(ArrayIndexOutOfBoundsException e) {
			System.out.println("caught an exception:"+e.getMessage());}
		break;
		     default:
		     System.out.println("invalid choice.please select 1or2");
		}
		System.out.println("do you want to continue? click y for yes or click n for no");
		c=sc.next().charAt(0);
		}
	while(c=='y'||c=='y');
	     System.out.println("code succesfully excecuted...");
		sc.close();
		}
	}
	
		
			
		

